In [1]:
import pandas as pd
import numpy as np

In [2]:
messages=pd.read_csv('SpamClassifier-master/smsspamcollection/SMSSpamCollection',
                    sep='\t',names=["label","message"])

In [3]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
# Preprocessing Steps
import nltk
import re
from nltk.stem import WordNetLemmatizer

In [5]:
lemmatizer = WordNetLemmatizer()

In [6]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/hackthebox/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
from nltk.corpus import stopwords

In [8]:
corpus = []
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review = review.lower()
    review=review.split()
    review = [lemmatizer.lemmatize(word,pos='v') for word in review if word not in (stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

In [9]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine get amore wat',
 'ok lar joke wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf live around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune callers press copy friends callertune',
 'winner value network customer select receivea prize reward claim call claim code kl valid hours',
 'mobile months u r entitle update latest colour mobiles camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cry enough today',
 'six chance win cash pound txt csh send cost p day days tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',


In [10]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [11]:
print(messages.iloc[:,1][0])

Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...


In [12]:
# Bag of words
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
cv = CountVectorizer(max_features=100,binary=True)
X = cv.fit_transform(corpus).toarray()

In [14]:
X.shape

(5572, 100)

In [15]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0

In [16]:
cv.vocabulary_

{'go': 25,
 'great': 27,
 'get': 23,
 'wat': 91,
 'ok': 59,
 'free': 22,
 'win': 95,
 'text': 79,
 'txt': 86,
 'say': 69,
 'already': 0,
 'think': 81,
 'hey': 30,
 'week': 93,
 'back': 5,
 'like': 41,
 'still': 75,
 'send': 71,
 'even': 19,
 'prize': 65,
 'claim': 10,
 'call': 7,
 'mobile': 50,
 'home': 32,
 'want': 90,
 'today': 83,
 'cash': 9,
 'day': 16,
 'reply': 67,
 'www': 97,
 'right': 68,
 'thank': 80,
 'take': 77,
 'time': 82,
 'use': 88,
 'message': 48,
 'com': 11,
 'oh': 58,
 'yes': 99,
 'make': 46,
 'way': 92,
 'feel': 20,
 'dont': 18,
 'miss': 49,
 'ur': 87,
 'try': 85,
 'da': 15,
 'lor': 43,
 'meet': 47,
 'really': 66,
 'know': 36,
 'lol': 42,
 'leave': 39,
 'love': 44,
 'amp': 1,
 'let': 40,
 'work': 96,
 'wait': 89,
 'yeah': 98,
 'tell': 78,
 'anything': 2,
 'please': 63,
 'msg': 52,
 'see': 70,
 'pls': 64,
 'need': 54,
 'tomorrow': 84,
 'hope': 33,
 'well': 94,
 'lt': 45,
 'gt': 28,
 'ask': 3,
 'keep': 35,
 'morning': 51,
 'happy': 29,
 'sorry': 74,
 'give': 24,
 'new'

In [17]:
cv = CountVectorizer(max_features=100,ngram_range=(1,1),binary=True)
X_unigram = cv.fit_transform(corpus).toarray()
X_unigram


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0

In [18]:
cv.vocabulary_

{'go': 25,
 'great': 27,
 'get': 23,
 'wat': 91,
 'ok': 59,
 'free': 22,
 'win': 95,
 'text': 79,
 'txt': 86,
 'say': 69,
 'already': 0,
 'think': 81,
 'hey': 30,
 'week': 93,
 'back': 5,
 'like': 41,
 'still': 75,
 'send': 71,
 'even': 19,
 'prize': 65,
 'claim': 10,
 'call': 7,
 'mobile': 50,
 'home': 32,
 'want': 90,
 'today': 83,
 'cash': 9,
 'day': 16,
 'reply': 67,
 'www': 97,
 'right': 68,
 'thank': 80,
 'take': 77,
 'time': 82,
 'use': 88,
 'message': 48,
 'com': 11,
 'oh': 58,
 'yes': 99,
 'make': 46,
 'way': 92,
 'feel': 20,
 'dont': 18,
 'miss': 49,
 'ur': 87,
 'try': 85,
 'da': 15,
 'lor': 43,
 'meet': 47,
 'really': 66,
 'know': 36,
 'lol': 42,
 'leave': 39,
 'love': 44,
 'amp': 1,
 'let': 40,
 'work': 96,
 'wait': 89,
 'yeah': 98,
 'tell': 78,
 'anything': 2,
 'please': 63,
 'msg': 52,
 'see': 70,
 'pls': 64,
 'need': 54,
 'tomorrow': 84,
 'hope': 33,
 'well': 94,
 'lt': 45,
 'gt': 28,
 'ask': 3,
 'keep': 35,
 'morning': 51,
 'happy': 29,
 'sorry': 74,
 'give': 24,
 'new'

In [20]:
cv_bigram = CountVectorizer(max_features=100,ngram_range=(2,2),binary=True)
X_bigram = cv_bigram.fit_transform(corpus).toarray()
cv_bigram.vocabulary_

{'free entry': 33,
 'claim call': 18,
 'call claim': 3,
 'free call': 32,
 'chance win': 17,
 'txt word': 91,
 'let know': 56,
 'go home': 37,
 'please call': 70,
 'lt gt': 60,
 'want go': 97,
 'like lt': 57,
 'sorry call': 83,
 'call later': 8,
 'ur award': 92,
 'come back': 23,
 'call customer': 4,
 'customer service': 25,
 'cash prize': 16,
 'po box': 72,
 'try contact': 88,
 'draw show': 30,
 'show prize': 82,
 'prize guarantee': 77,
 'guarantee call': 45,
 'valid hrs': 95,
 'select receive': 79,
 'private account': 75,
 'account statement': 0,
 'statement show': 84,
 'call identifier': 5,
 'identifier code': 52,
 'code expire': 22,
 'urgent mobile': 94,
 'caller prize': 12,
 'call landline': 7,
 'wat time': 98,
 'ur mob': 93,
 'go get': 36,
 'gud ni': 47,
 'send stop': 81,
 'get back': 35,
 'co uk': 21,
 'gud mrng': 46,
 'nice day': 66,
 'lt decimal': 59,
 'decimal gt': 27,
 'txt nokia': 89,
 'good morning': 40,
 'good night': 41,
 'camcorder reply': 13,
 'reply call': 78,
 'last 

In [21]:
cv_trigram = CountVectorizer(max_features=100,ngram_range=(3,3),binary=True)
X_trigram = cv_trigram.fit_transform(corpus).toarray()
cv_trigram.vocabulary_

{'call claim code': 6,
 'like lt gt': 45,
 'sorry call later': 81,
 'please call customer': 66,
 'call customer service': 7,
 'customer service representative': 23,
 'guarantee cash prize': 37,
 'draw show prize': 25,
 'show prize guarantee': 79,
 'prize guarantee call': 72,
 'specially select receive': 83,
 'speak live operator': 82,
 'live operator claim': 47,
 'private account statement': 70,
 'account statement show': 0,
 'call identifier code': 8,
 'identifier code expire': 42,
 'bonus caller prize': 4,
 'select receive award': 78,
 'match please call': 57,
 'urgent try contact': 97,
 'lt decimal gt': 49,
 'secret admirer look': 77,
 'admirer look make': 1,
 'look make contact': 48,
 'make contact find': 56,
 'contact find reveal': 20,
 'find reveal think': 30,
 'reveal think ur': 75,
 'think ur special': 88,
 'ur special call': 95,
 'draw txt music': 26,
 'www ldew com': 99,
 'anytime network mins': 2,
 'camcorder reply call': 13,
 'cant pick phone': 14,
 'pick phone right': 65,


In [23]:
cv_uni_bi = CountVectorizer(max_features=400,ngram_range=(1,2),binary=True)
X_uni_bi = cv_uni_bi.fit_transform(corpus).toarray()
cv_uni_bi.vocabulary_

{'go': 127,
 'point': 264,
 'great': 132,
 'world': 384,
 'get': 123,
 'wat': 368,
 'ok': 239,
 'lar': 172,
 'wif': 376,
 'free': 117,
 'entry': 106,
 'win': 377,
 'st': 316,
 'may': 203,
 'text': 329,
 'receive': 282,
 'question': 274,
 'txt': 354,
 'rate': 276,
 'apply': 17,
 'dun': 96,
 'say': 291,
 'early': 98,
 'already': 8,
 'think': 337,
 'live': 187,
 'around': 18,
 'though': 339,
 'hey': 149,
 'week': 371,
 'word': 382,
 'back': 26,
 'like': 184,
 'fun': 121,
 'still': 319,
 'xxx': 390,
 'send': 295,
 'even': 107,
 'speak': 314,
 'per': 249,
 'friends': 119,
 'network': 226,
 'customer': 74,
 'select': 294,
 'prize': 270,
 'claim': 55,
 'call': 42,
 'code': 60,
 'valid': 360,
 'mobile': 215,
 'latest': 176,
 'colour': 63,
 'camera': 45,
 'co': 58,
 'gonna': 129,
 'home': 153,
 'soon': 310,
 'want': 367,
 'talk': 326,
 'stuff': 321,
 'tonight': 346,
 'enough': 104,
 'today': 343,
 'chance': 50,
 'cash': 49,
 'pound': 266,
 'cost': 69,
 'day': 80,
 'days': 81,
 'reply': 284,
 'u

In [25]:
cv_bi_tri = CountVectorizer(max_features=400,ngram_range=(2,3),binary=True)
X_bi_tri = cv_bi_tri.fit_transform(corpus).toarray()
cv_bi_tri.vocabulary_

{'free entry': 106,
 'think go': 334,
 'claim call': 48,
 'call claim': 20,
 'claim code': 49,
 'update latest': 359,
 'latest colour': 174,
 'free call': 104,
 'call mobile': 30,
 'chance win': 47,
 'win cash': 390,
 'txt word': 352,
 'dont miss': 86,
 'let know': 177,
 'feel like': 100,
 'yeah get': 398,
 'reply yes': 288,
 'go home': 126,
 'anything lor': 5,
 'call reply': 36,
 'mobile free': 218,
 'free camcorder': 105,
 'please call': 262,
 'lt gt': 193,
 'miss call': 214,
 'want go': 380,
 'first time': 103,
 'like lt': 179,
 'like lt gt': 180,
 'sms ac': 309,
 'bx ip': 18,
 'sorry call': 311,
 'call later': 29,
 'later meet': 172,
 'sorry call later': 312,
 'award bonus': 11,
 'prize call': 275,
 'send ur': 303,
 'ur award': 360,
 'call free': 23,
 'thats cool': 333,
 'hi hi': 156,
 'come back': 60,
 'call customer': 21,
 'customer service': 80,
 'service representative': 304,
 'guarantee cash': 144,
 'cash prize': 46,
 'please call customer': 263,
 'call customer service': 22,


In [26]:
X_bi_tri

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0